/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as MocksRouteImport } from './routes/mocks'
import { Route as MockMockIdDashboardRouteImport } from './routes/mock.$mockId.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const MocksRoute = MocksRouteImport.update({
  id: '/mocks',
  path: '/mocks',
  getParentRoute: () => rootRouteImport,
} as any)
const MockMockIdDashboardRoute = MockMockIdDashboardRouteImport.update({
  id: '/mock/$mockId/dashboard',
  path: '/mock/$mockId/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/docs': typeof DocsRoute
  '/mocks': typeof MocksRoute
  '/mock/$mockId/dashboard': typeof MockMockIdDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/docs': typeof DocsRoute
  '/mocks': typeof MocksRoute
  '/mock/$mockId/dashboard': typeof MockMockIdDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/docs': typeof DocsRoute
  '/mocks': typeof MocksRoute
  '/mock/$mockId/dashboard': typeof MockMockIdDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create' | '/docs' | '/mocks' | '/mock/$mockId/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/docs' | '/mocks' | '/mock/$mockId/dashboard'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/docs'
    | '/mocks'
    | '/mock/$mockId/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DocsRoute: typeof DocsRoute
  MocksRoute: typeof MocksRoute
  MockMockIdDashboardRoute: typeof MockMockIdDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mocks': {
      id: '/mocks'
      path: '/mocks'
      fullPath: '/mocks'
      preLoaderRoute: typeof MocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/$mockId/dashboard': {
      id: '/mock/$mockId/dashboard'
      path: '/mock/$mockId/dashboard'
      fullPath: '/mock/$mockId/dashboard'
      preLoaderRoute: typeof MockMockIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DocsRoute: DocsRoute,
  MocksRoute: MocksRoute,
  MockMockIdDashboardRoute: MockMockIdDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
